AWSTemplateFormatVersion: 2010-09-09
Description: Template for creating analytics dashboard database

Parameters:
  StaticStackName:
    Type: String
    Default: analytics-dashboard
  ParamDBName:
    Type: String
    Default: analytics_staging
  ParamUsername:
    Type: String
    Default: analytics_dashboard_writer


Resources:
  Database:
    Type: AWS::RDS::DBInstance
    Properties:
      DBName: !Ref ParamDBName
      DBInstanceClass: db.t3.micro
      Engine: postgres
      AllocatedStorage: "10"
      BackupRetentionPeriod: 7
      DeleteAutomatedBackups: false
      PubliclyAccessible: true
      MasterUsername: !Ref ParamUsername
      MasterUserPassword: '{{resolve:secretsmanager:AnalyticsDashboardStagingDBPassword:SecretString}}'
      VPCSecurityGroups:
        - Fn::ImportValue:
            !Sub "${StaticStackName}-SGId"


Outputs:
  DatabaseHost:
    Description: Host Address of the Database
    Value: !GetAtt Database.Endpoint.Address
    Export:
      Name: analytics-staging-db
  DatabasePort:
    Description: Port of the Database
    Value: !GetAtt Database.Endpoint.Port
    Export:
      Name: analytics-staging-port


